import { Button, Color, Graphics, Label, Node, UITransform } from 'cc';
import { loadUiSprite } from '../../ui/UiAssets';
import { ensureArtCover, ensureArtStretch } from '../../ui/UiSprite';
import type { PveProfile } from '../core/PveProgressionTypes';
import { makeFlatButton, makeLabel } from './pveUiKit';

export type CampSection='MINGHEN'|'EQUIPMENT'|'INTEL'|'PROFESSION';
export interface CampViewCallbacks{onClose():void;onRefresh():void;onSelectProfession(id:keyof typeof PROFESSION_NAMES):void;onToggleMinghen(id:string):void;onTrackMinghen(id:string):void;onSavePreset():void;onToggleEquipment(instanceId:string):void;onManageEquipment(action:'TOGGLE_LOCK'|'ENHANCE'|'SELL',instanceId:string):void;onSectionChanged?(section:CampSection):void;}
const SECTION_LABELS:Record<CampSection,string>={MINGHEN:'命痕台',EQUIPMENT:'装备台',INTEL:'远征情报',PROFESSION:'角色区'};
const PROFESSION_NAMES={WARRIOR:'战士',ARCHER:'射手',RANGER:'游侠'} as const;

export class CampView{
 private readonly _overlay:Node;private readonly _content:Label;private readonly _title:Label;private readonly _actionRoot:Node;private _profile:PveProfile|null=null;private _section:CampSection='MINGHEN';private _minghenIndex=0;private _equipmentIndex=0;
 constructor(parent:Node,private readonly _callbacks:CampViewCallbacks){
  this._overlay=new Node('PersistentCampModal');this._overlay.setParent(parent);this._overlay.addComponent(UITransform).setContentSize(720,1280);
  const shade=this._overlay.addComponent(Graphics);shade.fillColor=new Color(0,8,24,205);shade.rect(-360,-640,720,1280);shade.fill();
  const panel=new Node('CampPanel');panel.setParent(this._overlay);panel.setPosition(0,10);panel.addComponent(UITransform).setContentSize(660,1040);const bg=panel.addComponent(Graphics);bg.fillColor=new Color(7,31,70,190);bg.roundRect(-330,-520,660,1040,22);bg.fill();bg.strokeColor=new Color(255,214,110,220);bg.lineWidth=2;bg.stroke();
  this._title=makeLabel(panel,0,450,560,60,34,new Color(255,220,100),Label.HorizontalAlign.CENTER);this._title.string='营地';this._title.isBold=true;
  const sections=Object.keys(SECTION_LABELS) as CampSection[];sections.forEach((section,index)=>makeFlatButton(panel,SECTION_LABELS[section],-225+index*150,370,138,58,()=>this.showSection(section),new Color(24,72,118,190),{noArt:true,border:new Color(255,214,110,190)}));
  this._content=makeLabel(panel,0,45,570,540,24,new Color(225,238,255),Label.HorizontalAlign.LEFT);this._content.verticalAlign=Label.VerticalAlign.TOP;this._content.overflow=Label.Overflow.SHRINK;
  this._actionRoot=new Node('SectionActions');this._actionRoot.setParent(panel);this._actionRoot.setPosition(0,-330);this._actionRoot.addComponent(UITransform).setContentSize(570,90);
  makeFlatButton(panel,'刷新',-140,-450,220,60,()=>this._callbacks.onRefresh(),new Color(30,100,105,190),{noArt:true,border:new Color(120,225,220)});
  makeFlatButton(panel,'返回大厅',140,-450,220,60,()=>this._callbacks.onClose(),new Color(105,65,45,190),{noArt:true,border:new Color(255,190,120)});
  void Promise.all([loadUiSprite('pve/backgrounds/bg_pve_camp'),loadUiSprite('pve/camp/panel_camp_main_9s')]).then(([background,panelArt])=>{if(!this._overlay.isValid)return;if(background)ensureArtCover(this._overlay,'CampBackground',background,720,1280).node.setSiblingIndex(0);if(panelArt)ensureArtStretch(panel,'CampPanelArt',panelArt,660,1040).node.setSiblingIndex(0);}).catch(()=>null);
 }
 setProfile(profile:PveProfile):void{this._profile=profile;this.showSection(this._section);}
 showLoading():void{this._content.string='正在整理营地档案…';}
 showError(message:string):void{this._content.string=`营地加载失败\n\n${message}`;}
 showSection(section:CampSection):void{this._section=section;this._title.string=`营地 · ${SECTION_LABELS[section]}`;this._callbacks.onSectionChanged?.(section);for(const child of [...this._actionRoot.children])child.destroy();const p=this._profile;if(!p){this.showLoading();return;}this._content.string=this._describe(section,p);const action=(text:string,x:number,w:number,callback:()=>void)=>makeFlatButton(this._actionRoot,text,x,0,w,58,callback,new Color(25,75,110,190),{noArt:true,border:new Color(255,214,110,190)});if(section==='MINGHEN'){const items=Object.values(p.minghenCollection);const selected=items[this._minghenIndex%Math.max(1,items.length)];action('上一枚',-230,100,()=>{this._minghenIndex=Math.max(0,this._minghenIndex-1);this.showSection(section);});action(p.minghenLoadout.some(x=>x.id===selected?.id)?'卸下':'装配',-115,100,()=>{if(selected)this._callbacks.onToggleMinghen(selected.id);});action('追踪',0,100,()=>{if(selected)this._callbacks.onTrackMinghen(selected.id);});action('存方案',115,100,()=>this._callbacks.onSavePreset());action('下一枚',230,100,()=>{this._minghenIndex=Math.min(Math.max(0,items.length-1),this._minghenIndex+1);this.showSection(section);});}if(section==='EQUIPMENT'){const items=p.equipmentInventory;const selected=items[this._equipmentIndex%Math.max(1,items.length)];const labels=['上一件',Object.values(p.equipmentLoadout).includes(selected?.instanceId??'')?'卸下':'穿戴','强化',selected?.locked?'解锁':'锁定','出售','下一件'];labels.forEach((text,index)=>action(text,-250+index*100,88,()=>{if(index===0){this._equipmentIndex=Math.max(0,this._equipmentIndex-1);this.showSection(section);}else if(index===5){this._equipmentIndex=Math.min(Math.max(0,items.length-1),this._equipmentIndex+1);this.showSection(section);}else if(selected){if(index===1)this._callbacks.onToggleEquipment(selected.instanceId);else this._callbacks.onManageEquipment((['','', 'ENHANCE','TOGGLE_LOCK','SELL'] as const)[index] as 'TOGGLE_LOCK'|'ENHANCE'|'SELL',selected.instanceId);}}));}if(section==='PROFESSION'){(Object.keys(PROFESSION_NAMES) as Array<keyof typeof PROFESSION_NAMES>).forEach((id,index)=>{const mastery=p.professions[id];const button=makeFlatButton(this._actionRoot,mastery.unlocked?`切换${PROFESSION_NAMES[id]}`:`${PROFESSION_NAMES[id]}未解锁`,-190+index*190,0,172,58,()=>{if(mastery.unlocked)this._callbacks.onSelectProfession(id);},id===p.selectedProfessionId?new Color(110,90,35,210):new Color(25,75,110,190),{noArt:true,border:new Color(255,214,110,190)});const component=button.getComponent(Button);if(component)component.interactable=mastery.unlocked;});}}
 destroy():void{this._overlay.destroy();}
 get node():Node{return this._overlay;}
 private _describe(section:CampSection,p:PveProfile):string{
  if(section==='MINGHEN'){const owned=Object.values(p.minghenCollection);const selected=owned[this._minghenIndex%Math.max(1,owned.length)];const equipped=p.minghenLoadout.map(x=>`${x.id} · ${['','I','II','III'][x.level]}`).join('\n')||'尚未装配';return`已收集 ${owned.length}/24　装配 ${p.minghenLoadout.length}/8　方案 ${p.minghenPresets.length}/5\n命尘 ${p.minghenDust}\n\n当前选择：${selected?`${selected.id} · Lv.${selected.level} · ${selected.copies}份`:'暂无命痕'}\n\n当前方案\n${equipped}\n\n追踪：${p.tracking?`${p.tracking.minghenId} · 第${p.tracking.floor}层 · ${p.tracking.state}`:'未选择'}`;}
  if(section==='EQUIPMENT'){const selected=p.equipmentInventory[this._equipmentIndex%Math.max(1,p.equipmentInventory.length)];const equipped=Object.entries(p.equipmentLoadout).map(([slot,id])=>`${slot}：${id}`).join('\n')||'尚未穿戴';return`永久背包 ${p.equipmentInventory.length}/60　金币 ${p.gold}\n\n当前选择：${selected?`${selected.definitionId} · ${selected.quality} · +${selected.enhanceLevel}${selected.locked?' · 已锁定':''}`:'暂无装备'}\n\n当前装备\n${equipped}\n\n固定装备没有随机词条；锁定或已穿戴装备不能出售。`;}
  if(section==='INTEL'){const floor=p.highestUnlockedFloor;return`下一目标：第 ${floor} 层\n最高通关：第 ${p.highestClearedFloor} 层\n\n${this._floorIntel(floor)}\n\n通关后可继续远征，或返回大厅重新调整命痕、装备和职业。`;}
  const lines=(Object.keys(PROFESSION_NAMES) as Array<keyof typeof PROFESSION_NAMES>).map(id=>{const m=p.professions[id];return`${id===p.selectedProfessionId?'▶':'　'}${PROFESSION_NAMES[id]}　${m.unlocked?`Lv.${m.level}　${m.xp} XP`:'未解锁'}\n　技法：${m.unlockedTechniqueIds.join('、')||'基础职业规则'}`;});return`${lines.join('\n\n')}\n\n熟练度只解锁主动技法与展示内容，不增加攻击、生命或护甲。`;
 }
 private _floorIntel(floor:number):string{const text=['','钥匙探索：找到钥匙并开启出口','精英猎杀：击败断旗哨长','波次生存：存活并清空三波敌人','目标追击：阻止传令兵逃离','突围抵达：穿过封锁并支付 1 AP 离开','据点清剿：摧毁三座号角祭坛','Boss 挑战：击败哥布林酋长'];return text[floor]??'后续章节情报尚未开放';}
}
