import { Button, Color, Graphics, Label, Node, UITransform } from 'cc';
import type { FloorChallengeRuntimeState } from '../core/FloorChallengeState';
import type { Chapter1PlayableState } from '../core/PersistentFloorBattleState';
import { makeFlatButton, makeLabel } from './pveUiKit';
export interface PersistentBattleViewCallbacks{onMove(direction:'UP'|'DOWN'|'LEFT'|'RIGHT'):void;onCell(x:number,y:number):void;onAttack():void;onInteract():void;onEndTurn():void;onSpirit():void;onCharge():void;onSettle():void;onContinue():void;onCamp():void;}
export class PersistentFloorBattleView{
 private readonly _root:Node;private readonly _hud:Label;private readonly _objective:Label;private readonly _message:Label;private readonly _board:Node;private readonly _charge:Label;private readonly _terminal:Node;private readonly _terminalText:Label;private _cells:Node[]=[];
 constructor(parent:Node,private readonly _callbacks:PersistentBattleViewCallbacks){this._root=new Node('PersistentFloorBattleRoot');this._root.setParent(parent);this._root.addComponent(UITransform).setContentSize(720,1280);const bg=this._root.addComponent(Graphics);bg.fillColor=new Color(4,18,42,255);bg.rect(-360,-640,720,1280);bg.fill();this._hud=makeLabel(this._root,0,570,670,54,26,new Color(255,226,130),Label.HorizontalAlign.CENTER);this._objective=makeLabel(this._root,0,515,650,44,22,new Color(205,230,255),Label.HorizontalAlign.CENTER);this._board=new Node('BattleBoard');this._board.setParent(this._root);this._board.setPosition(0,120);this._board.addComponent(UITransform).setContentSize(600,600);this._message=makeLabel(this._root,0,-225,650,42,21,new Color(190,220,240),Label.HorizontalAlign.CENTER);this._charge=makeLabel(this._root,0,-270,300,36,20,new Color(255,190,100),Label.HorizontalAlign.CENTER);const button=(text:string,x:number,y:number,w:number,cb:()=>void)=>makeFlatButton(this._root,text,x,y,w,58,cb,new Color(24,72,118,210),{noArt:true,border:new Color(255,214,110,190)});button('↑',-240,-360,80,()=>this._callbacks.onMove('UP'));button('↓',-240,-500,80,()=>this._callbacks.onMove('DOWN'));button('←',-330,-430,80,()=>this._callbacks.onMove('LEFT'));button('→',-150,-430,80,()=>this._callbacks.onMove('RIGHT'));button('攻击',-30,-375,130,()=>this._callbacks.onAttack());button('交互',115,-375,130,()=>this._callbacks.onInteract());button('结束回合',-30,-455,130,()=>this._callbacks.onEndTurn());button('灵气爆发',115,-455,130,()=>this._callbacks.onSpirit());button('蓄力',260,-415,110,()=>this._callbacks.onCharge());this._terminal=new Node('TerminalPanel');this._terminal.setParent(this._root);this._terminal.setPosition(0,20);this._terminal.addComponent(UITransform).setContentSize(620,500);const tg=this._terminal.addComponent(Graphics);tg.fillColor=new Color(5,25,55,245);tg.roundRect(-310,-250,620,500,20);tg.fill();tg.strokeColor=new Color(255,214,110);tg.lineWidth=3;tg.stroke();this._terminalText=makeLabel(this._terminal,0,120,540,180,30,new Color(255,230,150),Label.HorizontalAlign.CENTER);this._makeTerminalButton('结算',-180,-80,()=>this._callbacks.onSettle());this._makeTerminalButton('继续下一层',0,-80,()=>this._callbacks.onContinue());this._makeTerminalButton('返回营地',180,-80,()=>this._callbacks.onCamp());this._terminal.active=false;}
 private _makeTerminalButton(text:string,x:number,y:number,cb:()=>void){return makeFlatButton(this._terminal,text,x,y,160,60,cb,new Color(55,90,75,230),{noArt:true,border:new Color(255,214,110)});}
 refresh(state:FloorChallengeRuntimeState<Chapter1PlayableState>,charge:number,settled=false):void{const combat=state.battleState.combat;this._hud.string=`第 ${state.floor} 层 · 回合 ${state.turn}　HP ${state.resources.hp}/${state.resources.maxHp}　AP ${state.resources.ap}/${state.resources.maxAp}　灵气 ${state.resources.spirit}/100`;this._objective.string=`${state.battleState.map.name} · ${state.battleState.objective.kind} · ${state.battleState.objective.progress}/${state.battleState.objective.target}`;this._message.string=combat.message;this._charge.string=state.config.professionId==='WARRIOR'?`蓄力投入：${charge} AP`:`职业：${state.config.professionId}`;this._rebuildBoard(state);this._terminal.active=state.status!=='ACTIVE';if(this._terminal.active)this._terminalText.string=settled?(state.status==='CLEAR'?'结算完成\n可继续下一层或返回营地':'挑战已结算\n返回营地调整构筑后重试'):(state.status==='CLEAR'?'楼层通关！\n请领取本层奖励':'挑战失败\n永久资产不会损失');const buttons=this._terminal.children.filter(x=>x.name.startsWith('Btn_'));for(const b of buttons){if(b.name.includes('结算'))b.active=!settled;else if(b.name.includes('继续'))b.active=settled&&state.status==='CLEAR';else if(b.name.includes('返回'))b.active=settled;}}
 showError(message:string):void{this._message.string=message;}
 destroy():void{this._root.destroy();}
 private _rebuildBoard(state:FloorChallengeRuntimeState<Chapter1PlayableState>):void{for(const cell of this._cells)cell.destroy();this._cells=[];const map=state.battleState.map,size=map.size,cellSize=Math.floor(560/size),offset=(size-1)*cellSize/2;const wall=new Set(map.walls.map(x=>`${x.x},${x.y}`));for(let y=0;y<size;y+=1)for(let x=0;x<size;x+=1){const n=new Node(`Cell_${x}_${y}`);n.setParent(this._board);n.setPosition(x*cellSize-offset,offset-y*cellSize);n.addComponent(UITransform).setContentSize(cellSize-2,cellSize-2);const g=n.addComponent(Graphics);const monster=state.battleState.combat.monsters.find(m=>m.alive&&m.pos.x===x&&m.pos.y===y);const player=state.battleState.combat.playerPos.x===x&&state.battleState.combat.playerPos.y===y;const objective=map.objectiveCells.some(p=>p.x===x&&p.y===y),exit=map.exitCells.some(p=>p.x===x&&p.y===y);g.fillColor=wall.has(`${x},${y}`)?new Color(75,82,95):player?new Color(45,145,235):monster?new Color(180,60,55):objective?new Color(145,100,35):exit?new Color(45,145,85):new Color(18,48,75);g.rect(-(cellSize-2)/2,-(cellSize-2)/2,cellSize-2,cellSize-2);g.fill();const label=makeLabel(n,0,0,cellSize-4,cellSize-4,Math.max(13,Math.floor(cellSize*.24)),new Color(255,255,255),Label.HorizontalAlign.CENTER);label.string=player?'你':monster?`${monster.kind.slice(0,3)}\n${monster.hp}`:wall.has(`${x},${y}`)?'墙':objective?'目标':exit?'出口':'';n.addComponent(Button);n.on(Button.EventType.CLICK,()=>this._callbacks.onCell(x,y),n);this._cells.push(n);}}
}
