import { applyChapter1ObjectiveEvent } from './chapter1/Chapter1Runtime';
import type { Chapter1Coord } from './chapter1/Chapter1FloorCatalog';
import type { FloorChallengeRuntimeState } from './FloorChallengeState';
import type { Chapter1PlayableState, PlayableMonster } from './PersistentFloorBattleState';
import { createPlayableMonster } from './PersistentFloorBattleState';
import { createFixedEquipmentInstance, fixedWeaponAction, getFixedEquipmentDefinition } from './equipment/EquipmentDefinition';
import { scaledEquipmentStats } from './equipment/EquipmentProgression';
import { weaponCanTarget } from './equipment/WeaponGeometry';
import { commitProfessionAttack, commitProfessionMove, endProfessionTurn, previewProfessionAttack, type ProfessionAttackChoice } from './professions/ProfessionActionSystem';
import { gainSpirit, gainSpiritFromAttack } from './SpiritBurstSystem';
export type BattleDirection='UP'|'DOWN'|'LEFT'|'RIGHT';
const DELTA:Record<BattleDirection,Chapter1Coord>={UP:{x:0,y:-1},DOWN:{x:0,y:1},LEFT:{x:-1,y:0},RIGHT:{x:1,y:0}};
const posKey=(p:Chapter1Coord)=>`${p.x},${p.y}`;
function weaponOf(state:FloorChallengeRuntimeState<Chapter1PlayableState>){const item=state.battleState.combat.weapon??createFixedEquipmentInstance('starter','W01','COMMON');return{item,definition:getFixedEquipmentDefinition(item.definitionId)};}
function choiceFor(state:FloorChallengeRuntimeState<Chapter1PlayableState>,extraChargeAp=0):ProfessionAttackChoice{const id=state.config.professionId;return id==='WARRIOR'?{professionId:'WARRIOR',extraChargeAp}:id==='ARCHER'?{professionId:'ARCHER'}:{professionId:'RANGER'};}
export function movePersistentPlayer(state:FloorChallengeRuntimeState<Chapter1PlayableState>,direction:BattleDirection,now=Date.now()){if(state.status!=='ACTIVE')return state;const d=DELTA[direction],from=state.battleState.combat.playerPos,to={x:from.x+d.x,y:from.y+d.y};const map=state.battleState.map;if(to.x<0||to.y<0||to.x>=map.size||to.y>=map.size)return state;const blocked=new Set(map.walls.map(posKey));if(blocked.has(posKey(to))||state.battleState.combat.monsters.some(x=>x.alive&&posKey(x.pos)===posKey(to)))return state;const moved=commitProfessionMove(state,1,false,now);return{...moved,battleState:{...moved.battleState,combat:{...moved.battleState.combat,playerPos:to,message:'移动'}}};}
export function attackPersistentTarget(state:FloorChallengeRuntimeState<Chapter1PlayableState>,targetId:string,masteryLevel:number,extraChargeAp=0,now=Date.now()){if(state.status!=='ACTIVE')return state;const target=state.battleState.combat.monsters.find(x=>x.id===targetId&&x.alive);if(!target)return state;const{item,definition}=weaponOf(state);if(!weaponCanTarget(definition,state.battleState.combat.playerPos,target.pos))return state;const action=fixedWeaponAction(definition.id);const preview=previewProfessionAttack(state,action,masteryLevel,choiceFor(state,extraChargeAp));if(!preview.valid)return state;let next=commitProfessionAttack(state,preview,now);const stats=scaledEquipmentStats(item);const damage=Math.max(1,Math.round((10+stats.power)*(definition.fixed.damageCoefficient??1)*preview.damageMultiplier));const monsters=next.battleState.combat.monsters.map(x=>x.id===targetId?{...x,hp:Math.max(0,x.hp-damage),alive:x.hp-damage>0}:x);next={...next,battleState:{...next.battleState,combat:{...next.battleState.combat,monsters,message:`对${target.kind}造成${damage}伤害`}}};const killed=monsters.find(x=>x.id===targetId)?.alive===false;next=gainSpiritFromAttack(next,{hit:true,finalApCost:preview.apCost,killedRanks:killed?[target.role==='ELITE'||target.role==='CLIMAX'||target.role==='BOSS'?'ELITE':'NORMAL']:[]});if(killed){next=applyChapter1ObjectiveEvent(next,{type:'ENTITY_KILLED',entityId:targetId});if(target.kind==='ALTAR'&&next.status==='ACTIVE')next=applyChapter1ObjectiveEvent(next,{type:'ALTAR_DESTROYED',altarId:targetId});}return next;}
function spawnWave(state:FloorChallengeRuntimeState<Chapter1PlayableState>,wave:number){const map=state.battleState.map;const definitions=wave===2?[['GOBLIN_WARRIOR',0],['GOBLIN_ARCHER',1],['GOBLIN_ARCHER',2]]:[['FROST_GOBLIN',2],['GOBLIN_WARRIOR',3]];const spawned=definitions.map(([kind,index],i)=>createPlayableMonster({id:`wave${wave}_${i}`,kind:String(kind),pos:{...map.objectiveCells[Number(index)]!},rewardEligible:false,role:wave===3&&i===0?'CLIMAX':'NORMAL'}));let next={...state,battleState:{...state.battleState,combat:{...state.battleState.combat,wave,monsters:[...state.battleState.combat.monsters,...spawned],message:`第${wave}波出现`}}};next=applyChapter1ObjectiveEvent(next,{type:'WAVE_SPAWNED',wave,entityIds:spawned.map(x=>x.id)});return next;}
export function endPersistentPlayerTurn(state:FloorChallengeRuntimeState<Chapter1PlayableState>,now=Date.now()){if(state.status!=='ACTIVE')return state;let next=applyChapter1ObjectiveEvent(state,{type:'PLAYER_TURN_ENDED'},[],now);const spawn=next.battleState.pendingCommands.find(x=>x.type==='SPAWN_WAVE');if(spawn&&spawn.type==='SPAWN_WAVE')next=spawnWave(next,spawn.wave);let playerHp=next.resources.hp;let monsters=next.battleState.combat.monsters.map(x=>({...x,pos:{...x.pos}}));const player=next.battleState.combat.playerPos;for(const monster of monsters){if(!monster.alive||monster.attack<=0)continue;if(monster.id==='MESSENGER'){const exit=next.battleState.map.exitCells[0]!;for(let i=0;i<2;i+=1){if(monster.pos.x!==exit.x)monster.pos.x+=Math.sign(exit.x-monster.pos.x);else if(monster.pos.y!==exit.y)monster.pos.y+=Math.sign(exit.y-monster.pos.y);}if(posKey(monster.pos)===posKey(exit))next=applyChapter1ObjectiveEvent(next,{type:'TARGET_ESCAPED',entityId:'MESSENGER'});continue;}let distance=Math.abs(monster.pos.x-player.x)+Math.abs(monster.pos.y-player.y);if(distance<=monster.range){playerHp=Math.max(0,playerHp-monster.attack);continue;}const candidate={x:monster.pos.x+Math.sign(player.x-monster.pos.x),y:monster.pos.y};if(candidate.x===monster.pos.x)candidate.y+=Math.sign(player.y-monster.pos.y);if(!next.battleState.map.walls.some(w=>posKey(w)===posKey(candidate))&&!monsters.some(m=>m!==monster&&m.alive&&posKey(m.pos)===posKey(candidate)))monster.pos=candidate;distance=Math.abs(monster.pos.x-player.x)+Math.abs(monster.pos.y-player.y);if(distance<=monster.range)playerHp=Math.max(0,playerHp-monster.attack);}
 if(next.status!=='ACTIVE')return next;const actualDamage=Math.max(0,next.resources.hp-playerHp);next=endProfessionTurn(next,8,now);next={...next,resources:{...next.resources,hp:playerHp},battleState:{...next.battleState,pendingCommands:[],combat:{...next.battleState.combat,monsters,message:'新回合'}}};if(actualDamage>0)next=gainSpirit(next,{type:'PLAYER_DAMAGED',actualDamage});if(playerHp<=0)next=applyChapter1ObjectiveEvent(next,{type:'PLAYER_DIED'},[],now);return next;}
export function interactPersistentFloor(state:FloorChallengeRuntimeState<Chapter1PlayableState>,now=Date.now()){if(state.status!=='ACTIVE')return state;const pos=state.battleState.combat.playerPos,map=state.battleState.map;if(state.floor===1&&!state.battleState.combat.keyAcquired&&map.objectiveCells.some(x=>posKey(x)===posKey(pos))){let next={...state,battleState:{...state.battleState,combat:{...state.battleState.combat,keyAcquired:true,message:'取得钥匙'}}};return applyChapter1ObjectiveEvent(next,{type:'KEY_ACQUIRED',keyId:'KEY'},[],now);}if(map.exitCells.some(x=>posKey(x)===posKey(pos))){const paid=state.floor===5?1:0;if(state.resources.ap<paid)return state;let next={...state,resources:{...state.resources,ap:state.resources.ap-paid}};return applyChapter1ObjectiveEvent(next,{type:'EXIT_INTERACTED',apPaid:paid},[],now);}return state;}
