import { buildFloorSettlementRequest, resumeFloorRuntime, serializeFloorRuntime } from './FloorChallengeLifecycle';
import type { FloorChallengePlayerBaseline, FloorChallengeRuntimeState } from './FloorChallengeState';
import type { Chapter1BattleState } from './chapter1/Chapter1Runtime';
import { startChapter1Runtime } from './chapter1/Chapter1Runtime';
import type { FloorChallengeSnapshot, PveProfile, SaveFloorChallengeRuntimeRequest, SettleFloorChallengeRequest, StartFloorChallengeRequest } from './PveProgressionTypes';
export interface PersistentFloorFlowApi{loadProfile():Promise<{profile:PveProfile}>;loadActive():Promise<{challenge:FloorChallengeSnapshot|null}>;start(request:StartFloorChallengeRequest):Promise<{challenge:FloorChallengeSnapshot;resume:boolean}>;save(request:SaveFloorChallengeRuntimeRequest):Promise<unknown>;settle(request:SettleFloorChallengeRequest):Promise<{profile:PveProfile;rewards?:Record<string,unknown>}>;}
export interface PersistentFloorFlowState{profile:PveProfile;challenge:FloorChallengeSnapshot;runtime:FloorChallengeRuntimeState<Chapter1BattleState>;resumed:boolean}
export class PersistentFloorFlow{
 private _state:PersistentFloorFlowState|null=null;
 constructor(private readonly _api:PersistentFloorFlowApi,private readonly _baseline:FloorChallengePlayerBaseline={maxHp:280,maxAp:8}){}
 get state():PersistentFloorFlowState|null{return this._state;}
  async bootstrap():Promise<PersistentFloorFlowState>{const[{profile},{challenge:active}]=await Promise.all([this._api.loadProfile(),this._api.loadActive()]);let challenge=active,resumed=false;if(!challenge){const request:StartFloorChallengeRequest={floor:profile.highestUnlockedFloor,mode:'PROGRESSION',professionId:profile.selectedProfessionId,equipmentLoadout:{...profile.equipmentLoadout},minghenLoadout:profile.minghenLoadout.map(x=>({...x})),trackedMinghenId:null};const started=await this._api.start(request);challenge=started.challenge;resumed=started.resume;}else resumed=true;const runtime=challenge.runtimeSave?resumeFloorRuntime<Chapter1BattleState>(challenge,challenge.runtimeSave):startChapter1Runtime(challenge,this._baseline,false,Date.now(),profile);this._state={profile,challenge,runtime,resumed};return this._state;}
 updateRuntime(runtime:FloorChallengeRuntimeState<Chapter1BattleState>):void{if(!this._state||runtime.challengeId!==this._state.challenge.challengeId)throw new Error('FLOOR_FLOW_RUNTIME_MISMATCH');this._state={...this._state,runtime};}
 async save():Promise<void>{if(!this._state||this._state.runtime.status!=='ACTIVE')return;await this._api.save({challengeId:this._state.challenge.challengeId,serializedRuntime:serializeFloorRuntime(this._state.runtime)});}
 async settle(extra:Partial<SettleFloorChallengeRequest>={}):Promise<{profile:PveProfile;rewards?:Record<string,unknown>}>{if(!this._state)throw new Error('FLOOR_FLOW_NOT_READY');const request={...buildFloorSettlementRequest(this._state.runtime),...extra,challengeId:this._state.challenge.challengeId,status:this._state.runtime.status as Exclude<typeof this._state.runtime.status,'ACTIVE'>};const settled=await this._api.settle(request);this._state={...this._state,profile:settled.profile};return settled;}
  async continueNextFloor():Promise<PersistentFloorFlowState>{if(!this._state||this._state.runtime.status!=='CLEAR')throw new Error('FLOOR_NOT_CLEARED');if(this._state.profile.activeChallengeId)throw new Error('PREVIOUS_FLOOR_NOT_SETTLED');if(this._state.profile.highestUnlockedFloor>7)throw new Error('CHAPTER_ONE_COMPLETE');const request:StartFloorChallengeRequest={floor:this._state.profile.highestUnlockedFloor,mode:'PROGRESSION',professionId:this._state.profile.selectedProfessionId,equipmentLoadout:{...this._state.profile.equipmentLoadout},minghenLoadout:this._state.profile.minghenLoadout.map(x=>({...x})),trackedMinghenId:null};const started=await this._api.start(request);const runtime=startChapter1Runtime(started.challenge,this._baseline,false,Date.now(),this._state.profile);this._state={profile:this._state.profile,challenge:started.challenge,runtime,resumed:false};return this._state;}
 returnToCamp():void{if(this._state?.profile.activeChallengeId)throw new Error('ACTIVE_FLOOR_MUST_SETTLE_FIRST');this._state=null;}
}
