import { createBossObjective, createBreakthroughObjective, createChaseObjective, createEliteHuntObjective, createKeyExploreObjective, createPurgeObjective, createWaveSurvivalObjective, getChapter1Objective } from '../../assets/scripts/pve/core/objectives/Chapter1Objectives';
import { resumeObjective, serializeObjective } from '../../assets/scripts/pve/core/objectives/FloorObjective';
import { CHAPTER1_OPTIONAL_OBJECTIVES, completedOptionalObjectiveIds } from '../../assets/scripts/pve/core/objectives/Chapter1OptionalObjectives';

describe('chapter one objectives',()=>{
  test('floor 1 requires key before opening exit',()=>{const d=createKeyExploreObjective();let s=d.create();expect(d.apply(s,{type:'EXIT_INTERACTED',apPaid:0}).state.status).toBe('ACTIVE');let r=d.apply(s,{type:'KEY_ACQUIRED',keyId:'KEY'});expect(r.commands).toEqual([{type:'UNLOCK_EXIT'}]);r=d.apply(r.state,{type:'EXIT_INTERACTED',apPaid:0});expect(r.state.status).toBe('COMPLETE');});
  test('elite hunt completes immediately when target dies regardless of damage source',()=>{const d=createEliteHuntObjective();expect(d.apply(d.create(),{type:'ENTITY_KILLED',entityId:'BANNER_CAPTAIN',tags:['ENVIRONMENT_KILL']}).state.status).toBe('COMPLETE');});
  test('wave survival gives exactly one preparation turn and completes after last enemy',()=>{const d=createWaveSurvivalObjective();let r=d.apply(d.create(),{type:'WAVE_SPAWNED',wave:1,entityIds:['a','b']});r=d.apply(r.state,{type:'ENTITY_KILLED',entityId:'a'});r=d.apply(r.state,{type:'ENTITY_KILLED',entityId:'b'});expect(r.commands).toEqual([{type:'WARN_WAVE',wave:2}]);r=d.apply(r.state,{type:'PLAYER_TURN_ENDED'});expect(r.commands).toEqual([{type:'SPAWN_WAVE',wave:2}]);r=d.apply(r.state,{type:'WAVE_SPAWNED',wave:2,entityIds:['c']});r=d.apply(r.state,{type:'ENTITY_KILLED',entityId:'c'});r=d.apply(r.state,{type:'PLAYER_TURN_ENDED'});r=d.apply(r.state,{type:'WAVE_SPAWNED',wave:3,entityIds:['d']});r=d.apply(r.state,{type:'ENTITY_KILLED',entityId:'d'});expect(r.state.status).toBe('COMPLETE');});
  test('chase fails on escape and succeeds on messenger kill',()=>{const d=createChaseObjective();expect(d.apply(d.create(),{type:'TARGET_ESCAPED',entityId:'MESSENGER'}).state.status).toBe('FAILED');expect(d.apply(d.create(),{type:'ENTITY_KILLED',entityId:'MESSENGER'}).state.status).toBe('COMPLETE');});
  test('breakthrough charges one AP while simply standing at exit is insufficient',()=>{const d=createBreakthroughObjective();expect(d.apply(d.create(),{type:'EXIT_INTERACTED',apPaid:0}).state.status).toBe('ACTIVE');expect(d.apply(d.create(),{type:'EXIT_INTERACTED',apPaid:1}).state.status).toBe('COMPLETE');});
  test('purge waits for all three altars and all living summons',()=>{const d=createPurgeObjective();let s=d.create();s=d.apply(s,{type:'SUMMONED',entityId:'s1',sourceId:'ALTAR_1'}).state;for(const id of ['ALTAR_1','ALTAR_2','ALTAR_3'])s=d.apply(s,{type:'ALTAR_DESTROYED',altarId:id}).state;expect(s.status).toBe('ACTIVE');s=d.apply(s,{type:'ENTITY_KILLED',entityId:'s1'}).state;expect(s.status).toBe('COMPLETE');});
  test('boss death completes without key, exit, or clearing summons',()=>{const d=createBossObjective();expect(d.apply(d.create(),{type:'ENTITY_KILLED',entityId:'GOBLIN_CHIEF'}).state.status).toBe('COMPLETE');});
  test('all objectives fail on player death and ignore events after terminal state',()=>{for(let floor=1;floor<=7;floor+=1){const d=getChapter1Objective(floor);const failed=d.apply(d.create(),{type:'PLAYER_DIED'}).state;expect(failed.status).toBe('FAILED');expect(d.apply(failed,{type:'PLAYER_TURN_ENDED'}).state).toBe(failed);}});
  test('objective state serializes and rejects a different floor definition',()=>{const d=createWaveSurvivalObjective();const saved=serializeObjective(d.apply(d.create(),{type:'WAVE_SPAWNED',wave:1,entityIds:['a']}).state);expect(resumeObjective(saved,d).data.aliveIds).toEqual(['a']);expect(()=>resumeObjective(saved,createBreakthroughObjective())).toThrow('OBJECTIVE_SAVE_MISMATCH');});
  test('all 14 optional objectives are deterministic settlement checks',()=>{expect(CHAPTER1_OPTIONAL_OBJECTIVES).toHaveLength(14);expect(completedOptionalObjectiveIds(5,{fireGoblinKilled:true,exitRoute:'LEFT',collisionCount:2})).toEqual(['F5_FRONTAL_BREAK','F5_STONE_BREAK']);expect(completedOptionalObjectiveIds(5,{fireGoblinKilled:true,exitRoute:'RIGHT',collisionCount:1})).toEqual([]);});
});
