import { CHAPTER1_FLOORS, getChapter1FloorDefinition } from '../../assets/scripts/pve/core/chapter1/Chapter1FloorCatalog';
import { generateChapter1Floor, isReachable } from '../../assets/scripts/pve/core/chapter1/Chapter1FloorGenerator';
import { getChapter1Objective } from '../../assets/scripts/pve/core/objectives/Chapter1Objectives';
import { applyChapter1ObjectiveEvent, startChapter1Runtime } from '../../assets/scripts/pve/core/chapter1/Chapter1Runtime';
import type { FloorChallengeSnapshot } from '../../assets/scripts/pve/core/PveProgressionTypes';
import { createAltarEncounter, createGoblinChiefEncounter, damageGoblinChief, stepAltarEncounter, stepGoblinChief } from '../../assets/scripts/pve/core/chapter1/Chapter1Encounters';

describe('chapter one floor 1-7 vertical slice',()=>{
 test('all seven floors bind the matching objective and two optional objectives',()=>{expect(Object.keys(CHAPTER1_FLOORS)).toHaveLength(7);for(let floor=1;floor<=7;floor+=1){const d=getChapter1FloorDefinition(floor);expect(getChapter1Objective(floor).kind).toBe(d.objectiveKind);expect(d.optionalObjectiveIds).toHaveLength(2);expect(d.minghenIds.length).toBeGreaterThanOrEqual(3);expect(d.equipmentIds.length).toBeGreaterThanOrEqual(3);}});
 test.each(Array.from({length:7},(_,i)=>i+1))('floor %i is deterministic and critical cells remain reachable for 20 seeds',(floor)=>{for(let seed=1;seed<=20;seed+=1){const a=generateChapter1Floor(floor,seed,'PROGRESSION'),b=generateChapter1Floor(floor,seed,'PROGRESSION');expect(a).toEqual(b);for(const target of [...a.objectiveCells,...a.exitCells])expect(isReachable(a,a.player,target)).toBe(true);const occupied=new Set(a.walls.map(x=>`${x.x},${x.y}`));expect(occupied.has(`${a.player.x},${a.player.y}`)).toBe(false);for(const target of a.objectiveCells)expect(occupied.has(`${target.x},${target.y}`)).toBe(false);}});
 test('floor one tutorial suppresses random archer without changing key reachability',()=>{for(let seed=1;seed<=20;seed+=1){const floor=generateChapter1Floor(1,seed,'PROGRESSION',true);expect(floor.monsters).toHaveLength(2);expect(isReachable(floor,floor.player,floor.objectiveCells[0])).toBe(true);}});
 test('messenger unobstructed route is exactly six two-step monster turns',()=>{const d=getChapter1FloorDefinition(4);const messenger=d.criticalTargets[0],exit=d.exitCells[0];const distance=Math.abs(messenger.x-exit.x)+Math.abs(messenger.y-exit.y);expect(distance).toBe(12);expect(d.special?.unobstructedEscapeTurns).toBe(6);});
 test('floor six previews boss warning-cover loop with lower values',()=>{const f6=getChapter1FloorDefinition(6),f7=getChapter1FloorDefinition(7);expect(f6.fixedWalls.length).toBeGreaterThanOrEqual(4);expect(f6.special?.drumWarningTurns).toBe(1);expect(Number(f6.special?.drumDamage)).toBeLessThan(Number(f7.special?.bossHp));expect(f7.fixedWalls).toHaveLength(5);expect(f7.special?.safeRoutes).toBe(2);});
  test('boss configuration preserves warning time during enrage and caps summons',()=>{const boss=getChapter1FloorDefinition(7).special!;expect(boss).toMatchObject({bossHp:660,enrageHpRatio:.35,heavyInterval:3,heavyWarningTurns:1,summonNormal:1,summonEnraged:2,summonCap:6});});
  test('chapter runtime starts from challenge snapshot and objective events settle the floor',()=>{const snapshot:FloorChallengeSnapshot={challengeId:'c1',userId:'u1',floor:1,mode:'PROGRESSION',seed:2,status:'ACTIVE',config:{professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null},startedAt:1,updatedAt:1};let state=startChapter1Runtime(snapshot,{maxHp:280,maxAp:8},true,1);expect(state.battleState.map.monsters).toHaveLength(2);state=applyChapter1ObjectiveEvent(state,{type:'KEY_ACQUIRED',keyId:'KEY'},[],2);state=applyChapter1ObjectiveEvent(state,{type:'EXIT_INTERACTED',apPaid:0},['F1_FULL_SEARCH'],3);expect(state.status).toBe('CLEAR');expect(state.completedOptionalObjectiveIds).toEqual(['F1_FULL_SEARCH']);});
  test('chase escape ends as failed withdrawal while player death stays dead',()=>{const snapshot:FloorChallengeSnapshot={challengeId:'c4',userId:'u1',floor:4,mode:'PROGRESSION',seed:2,status:'ACTIVE',config:{professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null},startedAt:1,updatedAt:1};const active=startChapter1Runtime(snapshot,{maxHp:280,maxAp:8});expect(applyChapter1ObjectiveEvent(active,{type:'TARGET_ESCAPED',entityId:'MESSENGER'}).status).toBe('WITHDRAW');expect(applyChapter1ObjectiveEvent(active,{type:'PLAYER_DIED'}).status).toBe('DEAD');});
  test('altar encounter warns one round before drum hit and respects per-altar summon cap',()=>{let state=createAltarEncounter();let result=stepAltarEncounter(state);state=result.state;result=stepAltarEncounter(state);state=result.state;result=stepAltarEncounter(state);expect(result.commands.some(x=>x.type==='DRUM_WARNING')).toBe(true);state=result.state;result=stepAltarEncounter(state);expect(result.commands).toContainEqual(expect.objectContaining({type:'DRUM_HIT',damage:24,wallDamage:50}));for(let i=0;i<8;i+=1)state=stepAltarEncounter(state).state;expect(state.altars.every(x=>x.summonsAlive<=2)).toBe(true);});
  test('chief keeps warning time in enrage and horn respects six summon cap',()=>{let state=damageGoblinChief(createGoblinChiefEncounter(),430);expect(state.enraged).toBe(true);let warned=false,hit=false;for(let i=0;i<4;i+=1){const result=stepGoblinChief(state);state=result.state;warned ||= result.commands.some(x=>x.type==='HEAVY_WARNING');hit ||= result.commands.some(x=>x.type==='HEAVY_HIT');}expect(warned).toBe(true);expect(hit).toBe(true);expect(state.summonsAlive).toBe(6);expect(stepGoblinChief(state).commands.some(x=>x.type==='HORN_SUMMON')).toBe(false);});
});
