import { clearFloorRuntime } from '../../assets/scripts/pve/core/FloorChallengeLifecycle';
import { PersistentFloorFlow, type PersistentFloorFlowApi } from '../../assets/scripts/pve/core/PersistentFloorFlow';
import type { FloorChallengeSnapshot, PveProfile, StartFloorChallengeRequest } from '../../assets/scripts/pve/core/PveProgressionTypes';
function profile(overrides:Partial<PveProfile>={}):PveProfile{return{version:1,highestUnlockedFloor:1,highestClearedFloor:0,floorRecords:{},minghenCollection:{},minghenLoadout:[],minghenPresets:[],equipmentInventory:[],equipmentLoadout:{},gold:0,minghenDust:0,professions:{WARRIOR:{unlocked:true,xp:0,level:1,unlockedTechniqueIds:[]},ARCHER:{unlocked:false,xp:0,level:1,unlockedTechniqueIds:[]},RANGER:{unlocked:false,xp:0,level:1,unlockedTechniqueIds:[]}},selectedProfessionId:'WARRIOR',tracking:null,activeChallengeId:null,updatedAt:1,...overrides};}
function challenge(floor=1):FloorChallengeSnapshot{return{challengeId:`c${floor}`,userId:'u1',floor,mode:'PROGRESSION',seed:floor,status:'ACTIVE',config:{professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null},startedAt:1,updatedAt:1};}
function mockApi(initialProfile=profile(),active:FloorChallengeSnapshot|null=null){const starts:StartFloorChallengeRequest[]=[];const saves:string[]=[];const settles:unknown[]=[];let currentProfile=initialProfile;const api:PersistentFloorFlowApi={loadProfile:async()=>({profile:currentProfile}),loadActive:async()=>({challenge:active}),start:async request=>{starts.push(request);return{challenge:challenge(request.floor),resume:false};},save:async request=>{saves.push(request.serializedRuntime);},settle:async request=>{settles.push(request);currentProfile=profile({highestUnlockedFloor:2,highestClearedFloor:1,activeChallengeId:null});return{profile:currentProfile,rewards:{gold:20}};}};return{api,starts,saves,settles};}
describe('persistent floor flow',()=>{
 test('starts highest unlocked floor directly without stamina or old run state',async()=>{const m=mockApi();const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap();expect(m.starts[0]).toEqual({floor:1,mode:'PROGRESSION',professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null});expect(state.runtime.resources).toMatchObject({hp:280,ap:8,spirit:0});});
 test('resumes cloud runtime instead of starting another challenge',async()=>{const m=mockApi(profile({activeChallengeId:'c1'}),challenge());const first=new PersistentFloorFlow(m.api);const state=await first.bootstrap();await first.save();const active={...challenge(),runtimeSave:m.saves[0]};const resumedMocks=mockApi(profile({activeChallengeId:'c1'}),active);const resumed=await new PersistentFloorFlow(resumedMocks.api).bootstrap();expect(resumed.resumed).toBe(true);expect(resumed.runtime.challengeId).toBe(state.runtime.challengeId);expect(resumedMocks.starts).toHaveLength(0);});
 test('settles clear once then continues next floor with same camp configuration',async()=>{const m=mockApi();const flow=new PersistentFloorFlow(m.api);let state=await flow.bootstrap();flow.updateRuntime(clearFloorRuntime(state.runtime,['F1_FULL_SEARCH']));const settled=await flow.settle({selectedMinghenId:'M05',selectedEquipmentDefinitionId:'W01'});expect(settled.rewards).toEqual({gold:20});state=await flow.continueNextFloor();expect(m.starts.map(x=>x.floor)).toEqual([1,2]);expect(state.runtime.floor).toBe(2);});
 test('cannot return to camp before active floor settlement',async()=>{const m=mockApi(profile({activeChallengeId:'c1'}),challenge());const flow=new PersistentFloorFlow(m.api);await flow.bootstrap();expect(()=>flow.returnToCamp()).toThrow('ACTIVE_FLOOR_MUST_SETTLE_FIRST');});
});
