import { attackPersistentTarget, endPersistentPlayerTurn, interactPersistentFloor, movePersistentPlayer } from '../../assets/scripts/pve/core/PersistentFloorBattle';
import { startChapter1Runtime } from '../../assets/scripts/pve/core/chapter1/Chapter1Runtime';
import type { FloorChallengeSnapshot } from '../../assets/scripts/pve/core/PveProgressionTypes';
function runtime(floor:number){const snapshot:FloorChallengeSnapshot={challengeId:`c${floor}`,userId:'u',floor,mode:'PROGRESSION',seed:1,status:'ACTIVE',config:{professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null},startedAt:1,updatedAt:1};return startChapter1Runtime(snapshot,{maxHp:280,maxAp:8},true);}
describe('persistent floor battle adapter',()=>{
 test('movement spends AP and respects walls and bounds',()=>{const state=runtime(1);const moved=movePersistentPlayer(state,'DOWN');expect(moved.battleState.combat.playerPos).toEqual({x:1,y:7});expect(moved.resources.ap).toBe(7);expect(movePersistentPlayer(moved,'DOWN')).toBe(moved);});
 test('fixed weapon and profession attack kill routes objective events',()=>{let state=runtime(2);state={...state,battleState:{...state.battleState,combat:{...state.battleState.combat,playerPos:{x:3,y:3},monsters:state.battleState.combat.monsters.map(x=>x.id==='BANNER_CAPTAIN'?{...x,pos:{x:3,y:2},hp:1}:x)}}};state=attackPersistentTarget(state,'BANNER_CAPTAIN',1);expect(state.status).toBe('CLEAR');});
 test('floor one key and exit interaction complete without clearing monsters',()=>{let state=runtime(1);state={...state,battleState:{...state.battleState,combat:{...state.battleState.combat,playerPos:{...state.battleState.map.objectiveCells[0]}}}};state=interactPersistentFloor(state);expect(state.battleState.combat.keyAcquired).toBe(true);state={...state,battleState:{...state.battleState,combat:{...state.battleState.combat,playerPos:{...state.battleState.map.exitCells[0]}}}};state=interactPersistentFloor(state);expect(state.status).toBe('CLEAR');});
 test('clearing wave one warns then spawns wave two after preparation turn',()=>{let state=runtime(3);const ids=state.battleState.combat.monsters.map(x=>x.id);state={...state,battleState:{...state.battleState,combat:{...state.battleState.combat,playerPos:{x:3,y:3},monsters:state.battleState.combat.monsters.map((x,i)=>({...x,pos:i?{x:3,y:2}:{x:2,y:3},hp:1}))}}};state=attackPersistentTarget(state,ids[0],1);state=attackPersistentTarget(state,ids[1],1);expect(state.battleState.pendingCommands).toContainEqual({type:'WARN_WAVE',wave:2});state=endPersistentPlayerTurn(state);expect(state.battleState.combat.wave).toBe(2);expect(state.battleState.combat.monsters.some(x=>x.id.startsWith('wave2_'))).toBe(true);});
 test('monster attacks can kill player and settle death',()=>{let state=runtime(2);state={...state,resources:{...state.resources,hp:1},battleState:{...state.battleState,combat:{...state.battleState.combat,monsters:state.battleState.combat.monsters.map((x,i)=>i===0?{...x,pos:{x:3,y:6},range:1,attack:5}:x)}}};state=endPersistentPlayerTurn(state);expect(state.status).toBe('DEAD');expect(state.resources.hp).toBe(0);});
});
