import { clearFloorRuntime } from '../../assets/scripts/pve/core/FloorChallengeLifecycle';
import { PersistentFloorFlow, type PersistentFloorFlowApi } from '../../assets/scripts/pve/core/PersistentFloorFlow';
import type { FloorChallengeSnapshot, PveProfile, StartFloorChallengeRequest } from '../../assets/scripts/pve/core/PveProgressionTypes';
function profile(overrides:Partial<PveProfile>={}):PveProfile{return{version:1,highestUnlockedFloor:1,highestClearedFloor:0,highestClearedAt:null,floorRecords:{},minghenCollection:{},minghenLoadout:[],minghenPresets:[],equipmentInventory:[],equipmentLoadout:{},gold:0,minghenDust:0,professions:{WARRIOR:{unlocked:true,xp:0,level:1,unlockedTechniqueIds:[]},ARCHER:{unlocked:false,xp:0,level:1,unlockedTechniqueIds:[]},RANGER:{unlocked:false,xp:0,level:1,unlockedTechniqueIds:[]}},selectedProfessionId:'WARRIOR',tracking:null,activeChallengeId:null,stamina:60,staminaUpdatedAt:1,staminaNextRecoveryAt:null,tutorialFreeChallengeConsumed:false,updatedAt:1,...overrides};}
function challenge(floor=1):FloorChallengeSnapshot{return{challengeId:`c${floor}`,userId:'u1',floor,mode:'PROGRESSION',seed:floor,status:'ACTIVE',config:{professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null},startedAt:1,updatedAt:1};}
function mockApi(initialProfile=profile(),active:FloorChallengeSnapshot|null=null){const starts:StartFloorChallengeRequest[]=[];const saves:string[]=[];const settles:unknown[]=[];let currentProfile=initialProfile;const api:PersistentFloorFlowApi={loadProfile:async()=>({profile:currentProfile}),loadActive:async()=>({challenge:active}),start:async request=>{starts.push(request);const charged=currentProfile.tutorialFreeChallengeConsumed?5:0;currentProfile=profile({...currentProfile,activeChallengeId:`c${request.floor}`,stamina:currentProfile.stamina-charged,tutorialFreeChallengeConsumed:true});return{challenge:challenge(request.floor),profile:currentProfile,resume:false,charged};},save:async request=>{saves.push(request.serializedRuntime);},settle:async request=>{settles.push(request);currentProfile=profile({...currentProfile,highestUnlockedFloor:2,highestClearedFloor:1,activeChallengeId:null});return{profile:currentProfile,rewards:{gold:20}};}};return{api,starts,saves,settles};}
describe('persistent floor flow',()=>{
 test('starts highest unlocked floor directly without stamina or old run state',async()=>{const m=mockApi();const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap();expect(m.starts[0]).toEqual({floor:1,mode:'PROGRESSION',professionId:'WARRIOR',equipmentLoadout:{},minghenLoadout:[],trackedMinghenId:null});expect(state.runtime.resources).toMatchObject({hp:state.runtime.battleState.expedition.player.maxHp,spirit:0});expect(state.runtime.resources.ap).toBeGreaterThanOrEqual(9);expect(state.runtime.resources.ap).toBeLessThanOrEqual(14);});
 test('uses the authoritative profile returned after charging',async()=>{const m=mockApi(profile({stamina:12,tutorialFreeChallengeConsumed:true}));const state=await new PersistentFloorFlow(m.api).bootstrap();expect(state.profile.stamina).toBe(7);expect(state.profile.activeChallengeId).toBe('c1');});
 test('resumes cloud runtime instead of starting another challenge',async()=>{const m=mockApi(profile({activeChallengeId:'c1'}),challenge());const first=new PersistentFloorFlow(m.api);const state=await first.bootstrap();await first.save();const active={...challenge(),runtimeSave:m.saves[0]};const resumedMocks=mockApi(profile({activeChallengeId:'c1'}),active);const resumed=await new PersistentFloorFlow(resumedMocks.api).bootstrap();expect(resumed.resumed).toBe(true);expect(resumed.runtime.challengeId).toBe(state.runtime.challengeId);expect(resumedMocks.starts).toHaveLength(0);});
 test('explicit floor selection abandons a different active challenge',async()=>{const m=mockApi(profile({highestUnlockedFloor:4,highestClearedFloor:3,activeChallengeId:'c4'}),challenge(4));const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap(1);expect(m.starts[0]).toMatchObject({floor:1,abandonActive:true});expect(state.runtime.floor).toBe(1);expect(state.resumed).toBe(false);});
 test('settles clear once then continues next floor with same camp configuration',async()=>{const m=mockApi();const flow=new PersistentFloorFlow(m.api);let state=await flow.bootstrap();flow.updateRuntime(clearFloorRuntime(state.runtime,['F1_FULL_SEARCH']));const settled=await flow.settle({selectedMinghenId:'M05',selectedEquipmentDefinitionId:'生锈短刃'});expect(settled.rewards).toEqual({gold:20});state=await flow.continueNextFloor();expect(m.starts.map(x=>x.floor)).toEqual([1,2]);expect(state.runtime.floor).toBe(2);});
 test('retries settlement up to four times for a transient transaction conflict',async()=>{const m=mockApi();let calls=0;const original=m.api.settle;m.api.settle=async request=>{calls+=1;if(calls<3)throw new Error('document.update:fail -501001 ResourceUnavailable.TransactionBusy');return original(request);};const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap();flow.updateRuntime(clearFloorRuntime(state.runtime,[]));const settled=await flow.settle({selectedMinghenId:'M05'});expect(calls).toBe(3);expect(settled.profile.activeChallengeId).toBeNull();});
 test('exhausts conflict retries then surfaces the last transaction error',async()=>{const m=mockApi();let calls=0;m.api.settle=async()=>{calls+=1;throw new Error('TransactionBusy');};const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap();flow.updateRuntime(clearFloorRuntime(state.runtime,[]));await expect(flow.settle({selectedMinghenId:'M05'})).rejects.toThrow('TransactionBusy');expect(calls).toBe(4);});
 test('does not hide a genuine network failure behind a delayed retry',async()=>{const m=mockApi();let calls=0;m.api.settle=async()=>{calls+=1;throw new Error('NETWORK_TIMEOUT');};const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap();flow.updateRuntime(clearFloorRuntime(state.runtime,[]));await expect(flow.settle({selectedMinghenId:'M05'})).rejects.toThrow('NETWORK_TIMEOUT');expect(calls).toBe(1);});
 test('coalesces concurrent and repeated settlement calls for the same challenge',async()=>{const m=mockApi();let release:((value:{profile:PveProfile;rewards:{gold:number}})=>void)|undefined;m.api.settle=jest.fn(async()=>new Promise(resolve=>{release=resolve;}));const flow=new PersistentFloorFlow(m.api);const state=await flow.bootstrap();flow.updateRuntime(clearFloorRuntime(state.runtime,[]));const first=flow.settle({selectedMinghenId:'M05'});const second=flow.settle({selectedMinghenId:'M05'});await Promise.resolve();release?.({profile:profile({highestUnlockedFloor:2,highestClearedFloor:1,activeChallengeId:null}),rewards:{gold:20}});await expect(Promise.all([first,second])).resolves.toHaveLength(2);await flow.settle({selectedMinghenId:'M05'});expect(m.api.settle).toHaveBeenCalledTimes(1);});
 test('cannot return to camp before active floor settlement',async()=>{const m=mockApi(profile({activeChallengeId:'c1'}),challenge());const flow=new PersistentFloorFlow(m.api);await flow.bootstrap();expect(()=>flow.returnToCamp()).toThrow('ACTIVE_FLOOR_MUST_SETTLE_FIRST');});
});
