const MINGHEN_SOURCES={1:['M05','M06','M07'],2:['M01','M02','M09','M15'],3:['M03','M04','M10'],4:['M08','M11','M12','M16'],5:['M13','M14','M19'],6:['M17','M18','M20','M22'],7:['M21','M23','M24']};
const TRIAL_REQUIREMENTS={M01:{bleedApplied:6,bloodwalkKills:2},M02:{maxPoisonStacks:5,poisonKills:1},M03:{emberTriggers:5,burnConsumed:6},M04:{freezeOrStagger:3,followupActions:1},M05:{hiddenEdgeTriggers:3,overkillHalfHp:1},M06:{reserveApGained:4,reserveApSpentOnAttack:3},M07:{revengeTriggers:2,lowHpEliteKills:1},M08:{terrainEffectsTaken:3,terrainChargedTargets:3,cleared:1},M09:{huntTriggers:5,huntKills:2},M10:{catalystTargets:3,maxSimultaneousStatuses:3},M11:{shieldBreaks:3,rebuiltShieldPct:15},M12:{overhealShieldPct:30,shieldedEliteKills:1},M13:{collisions:4,doubleEnemyCollisions:2,discountKills:1},M14:{fullFlowChains:4,fourthActionFromRefund:1},M15:{retargetKillChain:3},M16:{backflowSpirit:45,backflowFilledBurst:1},M17:{spreadTargets:6,spreadStatusKills:2},M18:{detonations:5,detonationClimaxKills:1},M19:{secondaryDamage:100,doubleTransfers:1},M20:{multiToSingleChains:2,threeTargetHits:1},M21:{lowHpBossDamagePct:20,cleared:1},M22:{cloudStepTriggers:6,maxActionsInTurn:5},M23:{bloodforgeUses:4,bloodforgeKills:2,cleared:1},M24:{stillFieldBossHits:4,warningZoneHits:2,cleared:1}};
function sourceAllows(floor,id){return(MINGHEN_SOURCES[floor]??[]).includes(id);}
function levelFor(entry){if(entry.copies>=4&&entry.trialCompleted)return 3;if(entry.copies>=2)return 2;return 1;}
function grantCopy(collection,id){const old=collection[id]??{id,level:1,copies:0,trialCompleted:false};const next={...old,copies:old.copies+1};next.level=levelFor(next);return{...collection,[id]:next};}
function settleMinghen(profile,challenge,result,previous){let collection={...profile.minghenCollection};let tracking=profile.tracking;let dust=profile.minghenDust;let graduated=[...(previous.graduatedMinghenIds??[])];let grantedId=null;
 if(challenge.mode==='PROGRESSION'&&!previous.firstClearedAt&&result.selectedMinghenId){if(!sourceAllows(challenge.floor,result.selectedMinghenId)){const e=new Error('命痕不属于当前楼层主题池');e.code='PVE_INVALID_MINGHEN_REWARD';throw e;}collection=grantCopy(collection,result.selectedMinghenId);grantedId=result.selectedMinghenId;}
 if(challenge.mode==='HUNT'){const id=challenge.config.trackedMinghenId;if(!id||!sourceAllows(challenge.floor,id)||tracking?.minghenId!==id){const e=new Error('追踪状态与挑战快照不一致');e.code='PVE_TRACKING_MISMATCH';throw e;}const progressGain=1+(result.huntBonusAchieved?1:0);const old=collection[id]??{id,level:1,copies:1,trialCompleted:false};const copies=Math.min(4,old.copies+progressGain);const next={...old,copies};next.level=levelFor(next);collection={...collection,[id]:next};tracking=copies>=4?{floor:challenge.floor,minghenId:id,progress:4,state:'TRIAL_READY'}:{floor:challenge.floor,minghenId:id,progress:copies,state:'HUNT'};}
 if(challenge.mode==='TRIAL'){const id=challenge.config.trackedMinghenId;const old=collection[id];const evidence=result.trialEvidence??{};const requirement=TRIAL_REQUIREMENTS[id]??{};const evidencePassed=Object.entries(requirement).every(([key,value])=>Number.isInteger(evidence[key])&&evidence[key]>=value);if(!id||!old||old.copies<4||!challenge.config.minghenLoadout.some(x=>x.id===id)||!evidencePassed){const e=new Error('升格试炼条件未满足');e.code='PVE_TRIAL_NOT_COMPLETED';throw e;}const next={...old,trialCompleted:true,level:3};collection={...collection,[id]:next};tracking=null;graduated=[...new Set([...graduated,id])];dust+=20;grantedId=id;}
 return{collection,tracking,dust,graduated,grantedId};}
function beginTracking(profile,floor,id){if(!sourceAllows(floor,id))throw Object.assign(new Error('命痕来源层不匹配'),{code:'PVE_INVALID_TRACKING_SOURCE'});const owned=profile.minghenCollection[id];if(owned?.trialCompleted)throw Object.assign(new Error('命痕已经毕业'),{code:'PVE_MINGHEN_GRADUATED'});const copies=owned?.copies??0;return{...profile,tracking:{floor,minghenId:id,progress:Math.min(4,copies),state:copies>=4?'TRIAL_READY':'HUNT'}};}
module.exports={MINGHEN_SOURCES,TRIAL_REQUIREMENTS,sourceAllows,grantCopy,settleMinghen,beginTracking};
