export interface AltarState{id:string;hp:number;summonsAlive:number;destroyed:boolean}
export interface AltarEncounterState{monsterRound:number;altars:AltarState[];pendingDrumAltarId:string|null}
export type AltarCommand={type:'SUMMON';altarId:string;count:number}|{type:'DRUM_WARNING';altarId:string;radius:2}|{type:'DRUM_HIT';altarId:string;damage:24;wallDamage:50};
export function createAltarEncounter():AltarEncounterState{return{monsterRound:0,altars:['ALTAR_1','ALTAR_2','ALTAR_3'].map(id=>({id,hp:60,summonsAlive:0,destroyed:false})),pendingDrumAltarId:null};}
export function stepAltarEncounter(state:AltarEncounterState):{state:AltarEncounterState;commands:AltarCommand[]}{const round=state.monsterRound+1;const altars=state.altars.map(x=>({...x}));const commands:AltarCommand[]=[];let pending=state.pendingDrumAltarId;if(pending){commands.push({type:'DRUM_HIT',altarId:pending,damage:24,wallDamage:50});pending=null;}if(round%3===0){for(const altar of altars)if(!altar.destroyed&&altar.summonsAlive<2){altar.summonsAlive+=1;commands.push({type:'SUMMON',altarId:altar.id,count:1});}const alive=altars.filter(x=>!x.destroyed);if(alive.length){const altar=alive[(round/3-1)%alive.length]!;pending=altar.id;commands.push({type:'DRUM_WARNING',altarId:altar.id,radius:2});}}return{state:{monsterRound:round,altars,pendingDrumAltarId:pending},commands};}
/** 与 GoblinChief.ts / PveConstants 原机制对齐：狂暴阈值 170、号角上限 8。 */
export interface GoblinChiefState{hp:number;maxHp:660;monsterRound:number;enraged:boolean;pendingHeavy:boolean;summonsAlive:number}
export type ChiefCommand={type:'HEAVY_WARNING';radius:4}|{type:'HEAVY_HIT';wallBlocks:boolean}|{type:'HORN_SUMMON';count:number};
export function createGoblinChiefEncounter():GoblinChiefState{return{hp:660,maxHp:660,monsterRound:0,enraged:false,pendingHeavy:false,summonsAlive:0};}
export function damageGoblinChief(state:GoblinChiefState,damage:number):GoblinChiefState{const hp=Math.max(0,state.hp-Math.max(0,Math.trunc(damage)));return{...state,hp,enraged:state.enraged||hp<=170};}
export function stepGoblinChief(state:GoblinChiefState):{state:GoblinChiefState;commands:ChiefCommand[]}{const round=state.monsterRound+1;const commands:ChiefCommand[]=[];let pending=state.pendingHeavy;if(pending){commands.push({type:'HEAVY_HIT',wallBlocks:true});pending=false;}if(round%3===0){commands.push({type:'HEAVY_WARNING',radius:4});pending=true;}const desired=state.enraged?2:1;const count=Math.min(desired,Math.max(0,8-state.summonsAlive));if(count>0)commands.push({type:'HORN_SUMMON',count});return{state:{...state,monsterRound:round,pendingHeavy:pending,summonsAlive:state.summonsAlive+count},commands};}
