import { applyFloorDeath, clearFloorRuntime, startFloorRuntime, withdrawFloorRuntime } from '../FloorChallengeLifecycle';
import type { FloorChallengePlayerBaseline, FloorChallengeRuntimeState } from '../FloorChallengeState';
import type { FloorChallengeSnapshot } from '../PveProgressionTypes';
import { getChapter1Objective } from '../objectives/Chapter1Objectives';
import type { FloorObjectiveState, ObjectiveCommand, ObjectiveEvent } from '../objectives/FloorObjective';
import { generateChapter1Floor, type GeneratedChapter1Floor } from './Chapter1FloorGenerator';
export interface Chapter1BattleState{map:GeneratedChapter1Floor;objective:FloorObjectiveState;pendingCommands:ObjectiveCommand[]}
export function startChapter1Runtime(snapshot:FloorChallengeSnapshot,baseline:FloorChallengePlayerBaseline,firstTutorial=false,now=Date.now()):FloorChallengeRuntimeState<Chapter1BattleState>{if(snapshot.floor<1||snapshot.floor>7)throw new Error('CHAPTER1_FLOOR_OUT_OF_RANGE');const map=generateChapter1Floor(snapshot.floor,snapshot.seed,snapshot.mode,firstTutorial);const objective=getChapter1Objective(snapshot.floor).create();return startFloorRuntime(snapshot,baseline,{map,objective,pendingCommands:[]},now);}
export function applyChapter1ObjectiveEvent(state:FloorChallengeRuntimeState<Chapter1BattleState>,event:ObjectiveEvent,optionalObjectiveIds:readonly string[]=[],now=Date.now()):FloorChallengeRuntimeState<Chapter1BattleState>{if(state.status!=='ACTIVE')return state;const definition=getChapter1Objective(state.floor);const result=definition.apply(state.battleState.objective,event);const next={...state,battleState:{...state.battleState,objective:result.state,pendingCommands:result.commands},updatedAt:now};if(result.state.status==='COMPLETE')return clearFloorRuntime(next,optionalObjectiveIds,now);if(result.state.status==='FAILED'){if(event.type==='PLAYER_DIED')return applyFloorDeath(next,now);return withdrawFloorRuntime(next,now);}return next;}
export function consumeChapter1Commands(state:FloorChallengeRuntimeState<Chapter1BattleState>):{state:FloorChallengeRuntimeState<Chapter1BattleState>;commands:ObjectiveCommand[]}{return{state:{...state,battleState:{...state.battleState,pendingCommands:[]}},commands:[...state.battleState.pendingCommands]};}
