import { applyFloorDeath, clearFloorRuntime, startFloorRuntime, withdrawFloorRuntime } from '../FloorChallengeLifecycle';
import type { FloorChallengePlayerBaseline, FloorChallengeRuntimeState } from '../FloorChallengeState';
import type { FloorChallengeSnapshot } from '../PveProgressionTypes';
import { getChapter1Objective } from '../objectives/Chapter1Objectives';
import type { FloorObjectiveState, ObjectiveCommand, ObjectiveEvent } from '../objectives/FloorObjective';
import { generateChapter1Floor, type GeneratedChapter1Floor } from './Chapter1FloorGenerator';
import { createPersistentCombatState, type Chapter1PlayableState } from '../PersistentFloorBattleState';
import type { PveProfile } from '../PveProgressionTypes';
export type Chapter1BattleState=Chapter1PlayableState;
export function startChapter1Runtime(snapshot:FloorChallengeSnapshot,baseline:FloorChallengePlayerBaseline,firstTutorial=false,now=Date.now(),profile?:PveProfile):FloorChallengeRuntimeState<Chapter1BattleState>{if(snapshot.floor<1||snapshot.floor>7)throw new Error('CHAPTER1_FLOOR_OUT_OF_RANGE');const map=generateChapter1Floor(snapshot.floor,snapshot.seed,snapshot.mode,firstTutorial);const combat=createPersistentCombatState(map,profile);let objective=getChapter1Objective(snapshot.floor).create();if(snapshot.floor===3)objective=getChapter1Objective(3).apply(objective,{type:'WAVE_SPAWNED',wave:1,entityIds:combat.monsters.map(x=>x.id)}).state;return startFloorRuntime(snapshot,baseline,{map,objective,pendingCommands:[],combat},now);}
export function applyChapter1ObjectiveEvent(state:FloorChallengeRuntimeState<Chapter1BattleState>,event:ObjectiveEvent,optionalObjectiveIds:readonly string[]=[],now=Date.now()):FloorChallengeRuntimeState<Chapter1BattleState>{if(state.status!=='ACTIVE')return state;const definition=getChapter1Objective(state.floor);const result=definition.apply(state.battleState.objective,event);const next={...state,battleState:{...state.battleState,objective:result.state,pendingCommands:result.commands},updatedAt:now};if(result.state.status==='COMPLETE')return clearFloorRuntime(next,optionalObjectiveIds,now);if(result.state.status==='FAILED'){if(event.type==='PLAYER_DIED')return applyFloorDeath(next,now);return withdrawFloorRuntime(next,now);}return next;}
export function consumeChapter1Commands(state:FloorChallengeRuntimeState<Chapter1BattleState>):{state:FloorChallengeRuntimeState<Chapter1BattleState>;commands:ObjectiveCommand[]}{return{state:{...state,battleState:{...state.battleState,pendingCommands:[]}},commands:[...state.battleState.pendingCommands]};}
