import type { ObjectiveKind } from '../objectives/FloorObjective';
export interface Chapter1Coord{x:number;y:number}
export interface Chapter1MonsterSpawn{id:string;kind:string;pos:Chapter1Coord;role?:'NORMAL'|'ELITE'|'CLIMAX'|'BOSS'|'OBJECTIVE';rewardEligible:boolean}
export interface Chapter1FloorDefinition{floor:number;name:string;size:number;objectiveKind:ObjectiveKind;player:Chapter1Coord;criticalTargets:Chapter1Coord[];exitCells:Chapter1Coord[];fixedWalls:Chapter1Coord[];randomRockCandidates:Chapter1Coord[];randomRockCount:number;fixedMonsters:Chapter1MonsterSpawn[];randomMonsterPools:readonly string[][];minghenIds:string[];equipmentIds:string[];optionalObjectiveIds:string[];special?:Record<string,number|boolean|string|readonly number[]>}
const c=(x:number,y:number):Chapter1Coord=>({x,y});
export const CHAPTER1_FLOORS:Record<number,Chapter1FloorDefinition>={
1:{floor:1,name:'林缘钥哨',size:8,objectiveKind:'KEY_EXPLORE',player:c(1,6),criticalTargets:[c(6,1),c(6,2)],exitCells:[c(1,1)],fixedWalls:[c(3,2),c(3,3),c(3,4),c(3,5)],randomRockCandidates:[c(5,5),c(6,5),c(5,6),c(2,3)],randomRockCount:2,fixedMonsters:[{id:'f1_w1',kind:'GOBLIN_WARRIOR',pos:c(4,2),rewardEligible:true},{id:'f1_w2',kind:'GOBLIN_WARRIOR',pos:c(5,4),rewardEligible:true}],randomMonsterPools:[[],['GOBLIN_ARCHER']],minghenIds:['M05','M06','M07'],equipmentIds:['W01','A01','S01'],optionalObjectiveIds:['F1_FULL_SEARCH','F1_STEADY_START']},
2:{floor:2,name:'断旗猎场',size:8,objectiveKind:'ELITE_HUNT',player:c(3,7),criticalTargets:[c(3,2)],exitCells:[],fixedWalls:[c(2,2),c(4,2),c(2,3),c(4,3)],randomRockCandidates:[c(1,4),c(5,4),c(1,5),c(5,5)],randomRockCount:2,fixedMonsters:[{id:'BANNER_CAPTAIN',kind:'BANNER_CAPTAIN',pos:c(3,2),role:'ELITE',rewardEligible:true},{id:'f2_w',kind:'GOBLIN_WARRIOR',pos:c(2,4),rewardEligible:true},{id:'f2_a',kind:'GOBLIN_ARCHER',pos:c(4,4),rewardEligible:true}],randomMonsterPools:[['GOBLIN_WARRIOR'],['GOBLIN_ARCHER']],minghenIds:['M01','M02','M09','M15'],equipmentIds:['W03','W04','H01'],optionalObjectiveIds:['F2_DECAPITATE','F2_SUPPRESS_FIRE']},
3:{floor:3,name:'夜袭围营',size:8,objectiveKind:'WAVE_SURVIVAL',player:c(3,4),criticalTargets:[c(0,0),c(7,0),c(0,7),c(7,7)],exitCells:[],fixedWalls:[c(2,2),c(5,2),c(3,5)],randomRockCandidates:[],randomRockCount:0,fixedMonsters:[],randomMonsterPools:[],minghenIds:['M03','M04','M10'],equipmentIds:['W05','W07','A02','H02'],optionalObjectiveIds:['F3_HOLD_GROUND','F3_LAST_WAVE'],special:{waveCount:3,prepareTurns:1}},
4:{floor:4,name:'夺令追踪',size:8,objectiveKind:'CHASE',player:c(0,7),criticalTargets:[c(1,6)],exitCells:[c(7,0),c(6,0)],fixedWalls:[c(4,4),c(4,5)],randomRockCandidates:[],randomRockCount:0,fixedMonsters:[{id:'MESSENGER',kind:'MESSENGER',pos:c(1,6),role:'OBJECTIVE',rewardEligible:true},{id:'f4_w',kind:'GOBLIN_WARRIOR',pos:c(3,5),rewardEligible:true},{id:'f4_a',kind:'GOBLIN_ARCHER',pos:c(5,3),rewardEligible:true}],randomMonsterPools:[['GOBLIN_WARRIOR'],['GOBLIN_SENTINEL']],minghenIds:['M08','M11','M12','M16'],equipmentIds:['W06','S03','T01','T02'],optionalObjectiveIds:['F4_CUT_ESCAPE','F4_WALK_FIRE'],special:{messengerMove:2,unobstructedEscapeTurns:6,burningTiles:4}},
5:{floor:5,name:'碎石封锁',size:8,objectiveKind:'BREAKTHROUGH',player:c(3,7),criticalTargets:[],exitCells:[c(1,0),c(3,0),c(6,0)],fixedWalls:[c(2,1),c(2,2),c(2,4),c(2,5),c(5,2),c(5,3),c(5,5)],randomRockCandidates:[c(3,3),c(4,4),c(3,5)],randomRockCount:2,fixedMonsters:[{id:'f5_fire',kind:'FIRE_GOBLIN',pos:c(1,3),role:'ELITE',rewardEligible:true},{id:'f5_a1',kind:'GOBLIN_ARCHER',pos:c(3,3),rewardEligible:true},{id:'f5_a2',kind:'GOBLIN_ARCHER',pos:c(6,3),rewardEligible:true}],randomMonsterPools:[['GOBLIN_WARRIOR','GOBLIN_WARRIOR']],minghenIds:['M13','M14','M19'],equipmentIds:['W02','A03','S02'],optionalObjectiveIds:['F5_FRONTAL_BREAK','F5_STONE_BREAK']},
6:{floor:6,name:'号角祭坛',size:8,objectiveKind:'PURGE',player:c(3,7),criticalTargets:[c(1,1),c(6,1),c(3,5)],exitCells:[],fixedWalls:[c(2,5),c(2,4),c(4,3),c(5,3)],randomRockCandidates:[],randomRockCount:0,fixedMonsters:[{id:'f6_s',kind:'GOBLIN_SENTINEL',pos:c(3,3),rewardEligible:true},{id:'f6_w',kind:'GOBLIN_WARRIOR',pos:c(1,4),rewardEligible:true},{id:'f6_a',kind:'GOBLIN_ARCHER',pos:c(6,4),rewardEligible:true}],randomMonsterPools:[],minghenIds:['M17','M18','M20','M22'],equipmentIds:['H03','T03','W01','A01','S01','W03','W04','H01','W05','W07','A02','H02','W06','S03','T01','T02','W02','A03','S02'],optionalObjectiveIds:['F6_SILENCE','F6_WALL_COVER'],special:{altarCount:3,altarHp:60,summonInterval:3,summonCapPerAltar:2,drumInterval:3,drumWarningTurns:1,drumDamage:24,drumRadius:2,wallDamage:50}},
7:{floor:7,name:'酋长大营',size:10,objectiveKind:'BOSS',player:c(5,9),criticalTargets:[c(5,1)],exitCells:[],fixedWalls:[c(3,4),c(4,4),c(6,4),c(7,4),c(5,6)],randomRockCandidates:[],randomRockCount:0,fixedMonsters:[{id:'GOBLIN_CHIEF',kind:'GOBLIN_CHIEF',pos:c(5,1),role:'BOSS',rewardEligible:true}],randomMonsterPools:[],minghenIds:['M21','M23','M24'],equipmentIds:['B01','B02','B03'],optionalObjectiveIds:['F7_STONE_WEAPON','F7_SILENT_HORN'],special:{bossHp:660,enrageHpRatio:.35,heavyInterval:3,heavyWarningTurns:1,heavyRadius:4,summonNormal:1,summonEnraged:2,summonCap:6,safeRoutes:2}},
};
export function getChapter1FloorDefinition(floor:number):Chapter1FloorDefinition{const value=CHAPTER1_FLOORS[floor];if(!value)throw new Error('CHAPTER1_FLOOR_NOT_FOUND');return value;}
